/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;

import Modelo.Pessoa;
import java.util.ArrayList;

/**
 *
 * @author warml
 */
public class SistemaReceitaFederalView extends javax.swing.JFrame {
    private ArrayList<Pessoa> pessoas;
    /**
     * Creates new form SistemaReceitaFederalView
     */
    public SistemaReceitaFederalView() {
        this.pessoas = new ArrayList<Pessoa>();
        initComponents();
    }
    
    public ArrayList<Pessoa> getPessoas(){
        return this.pessoas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbReceitaFedeal = new javax.swing.JMenuBar();
        mnCadastros = new javax.swing.JMenu();
        miPessoaFisica = new javax.swing.JMenuItem();
        miPessoaJuridica = new javax.swing.JMenuItem();
        mnRelatorios = new javax.swing.JMenu();
        miPessoa = new javax.swing.JMenuItem();
        miPessoasImposto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Receita Federal");

        mnCadastros.setText("Cadastros");

        miPessoaFisica.setText("Pessoas Físicas");
        miPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPessoaFisicaActionPerformed(evt);
            }
        });
        mnCadastros.add(miPessoaFisica);

        miPessoaJuridica.setText("Pessoas Jurídicas");
        miPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPessoaJuridicaActionPerformed(evt);
            }
        });
        mnCadastros.add(miPessoaJuridica);

        mbReceitaFedeal.add(mnCadastros);

        mnRelatorios.setText("Relatórios");

        miPessoa.setText("Pessoas");
        miPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPessoaActionPerformed(evt);
            }
        });
        mnRelatorios.add(miPessoa);

        miPessoasImposto.setText("Pessoas com Imposto");
        miPessoasImposto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPessoasImpostoActionPerformed(evt);
            }
        });
        mnRelatorios.add(miPessoasImposto);

        mbReceitaFedeal.add(mnRelatorios);

        setJMenuBar(mbReceitaFedeal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPessoaFisicaActionPerformed
        CadastroPessoaFisicaView cadPessoaFisicaView = new CadastroPessoaFisicaView(this);
        cadPessoaFisicaView.setVisible(true);
    }//GEN-LAST:event_miPessoaFisicaActionPerformed

    private void miPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPessoaJuridicaActionPerformed
        CadastroPessoaJuridicaView cadPessoaJuridicaView = new CadastroPessoaJuridicaView(this);
        cadPessoaJuridicaView.setVisible(true);
    }//GEN-LAST:event_miPessoaJuridicaActionPerformed

    private void miPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPessoaActionPerformed
        RelatorioPessoasView relPessoasView = new RelatorioPessoasView(this);
        relPessoasView.setVisible(true);
    }//GEN-LAST:event_miPessoaActionPerformed

    private void miPessoasImpostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPessoasImpostoActionPerformed
        RelatorioPessoasImpostosView relPessoasImpostosView = new RelatorioPessoasImpostosView(this);
        relPessoasImpostosView.setVisible(true);
    }//GEN-LAST:event_miPessoasImpostoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaReceitaFederalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaReceitaFederalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaReceitaFederalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaReceitaFederalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaReceitaFederalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mbReceitaFedeal;
    private javax.swing.JMenuItem miPessoa;
    private javax.swing.JMenuItem miPessoaFisica;
    private javax.swing.JMenuItem miPessoaJuridica;
    private javax.swing.JMenuItem miPessoasImposto;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenu mnRelatorios;
    // End of variables declaration//GEN-END:variables
}
