/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;

import Modelo.Pessoa;
import java.util.ArrayList;

/**
 *
 * @author warml
 */
public class SistemaReceitaFederalView extends javax.swing.JFrame {

    private ArrayList<Pessoa> pessoas;
    /**
     * Creates new form SistemaReceitaFederalView
     */
    public SistemaReceitaFederalView() {
        this.pessoas = new ArrayList<Pessoa>();
        initComponents();
    }
    
    public ArrayList<Pessoa> getPessoas(){
        return this.pessoas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbSistemaReceitaFederal = new javax.swing.JMenuBar();
        mbCadastros = new javax.swing.JMenu();
        miCadastroPessoaFisica = new javax.swing.JMenuItem();
        miCadastroPessoaJuridica = new javax.swing.JMenuItem();
        mbRelatorios = new javax.swing.JMenu();
        miRelatorioPessoa = new javax.swing.JMenuItem();
        miRelatorioPessoasImposto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema da Receita Federal");

        mbCadastros.setText("Cadastros");

        miCadastroPessoaFisica.setText("Pessoa Física");
        miCadastroPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroPessoaFisicaActionPerformed(evt);
            }
        });
        mbCadastros.add(miCadastroPessoaFisica);

        miCadastroPessoaJuridica.setText("Pessoa Jurídica");
        miCadastroPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroPessoaJuridicaActionPerformed(evt);
            }
        });
        mbCadastros.add(miCadastroPessoaJuridica);

        mbSistemaReceitaFederal.add(mbCadastros);

        mbRelatorios.setText("Relatórios");

        miRelatorioPessoa.setText("Pessoas");
        miRelatorioPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatorioPessoaActionPerformed(evt);
            }
        });
        mbRelatorios.add(miRelatorioPessoa);

        miRelatorioPessoasImposto.setText("Pessoas com Imposto");
        miRelatorioPessoasImposto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatorioPessoasImpostoActionPerformed(evt);
            }
        });
        mbRelatorios.add(miRelatorioPessoasImposto);

        mbSistemaReceitaFederal.add(mbRelatorios);

        setJMenuBar(mbSistemaReceitaFederal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCadastroPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroPessoaFisicaActionPerformed
        CadastroPessoaFisicaView cadPessoaFisicaView = new CadastroPessoaFisicaView(this);
        cadPessoaFisicaView.setVisible(true);
    }//GEN-LAST:event_miCadastroPessoaFisicaActionPerformed

    private void miCadastroPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroPessoaJuridicaActionPerformed
        CadastroPessoaJuridicaView cadPessoaJuridicaView = new CadastroPessoaJuridicaView(this);
        cadPessoaJuridicaView.setVisible(true);
    }//GEN-LAST:event_miCadastroPessoaJuridicaActionPerformed

    private void miRelatorioPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioPessoaActionPerformed
        RelatorioPessoasView relPessoaView = new RelatorioPessoasView(this);
        relPessoaView.setVisible(true);
    }//GEN-LAST:event_miRelatorioPessoaActionPerformed

    private void miRelatorioPessoasImpostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioPessoasImpostoActionPerformed
       RelatorioPessoasImpostosView relPessoaImpostoView = new RelatorioPessoasImpostosView(this);
       relPessoaImpostoView.setVisible(true);
    }//GEN-LAST:event_miRelatorioPessoasImpostoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaReceitaFederalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaReceitaFederalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaReceitaFederalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaReceitaFederalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaReceitaFederalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mbCadastros;
    private javax.swing.JMenu mbRelatorios;
    private javax.swing.JMenuBar mbSistemaReceitaFederal;
    private javax.swing.JMenuItem miCadastroPessoaFisica;
    private javax.swing.JMenuItem miCadastroPessoaJuridica;
    private javax.swing.JMenuItem miRelatorioPessoa;
    private javax.swing.JMenuItem miRelatorioPessoasImposto;
    // End of variables declaration//GEN-END:variables
}
