/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;

import Modelo.Categoria;
import Modelo.Produto;
import java.util.ArrayList;

/**
 *
 * @author warml
 */
public class SistemaVendasView extends javax.swing.JFrame {

    private ArrayList<Categoria> categorias;
    private ArrayList<Produto> produtos;
    /**
     * Creates new form SistemaVendasView
     */
    public SistemaVendasView() {
        this.categorias = new ArrayList<Categoria>();
        this.produtos = new ArrayList<Produto>();
        initComponents();
    }
    
    public ArrayList<Categoria> getCategorias(){
        return this.categorias;
    }
    
    public ArrayList<Produto> getProdutos(){
        return this.produtos;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbSistemaVendas = new javax.swing.JMenuBar();
        mbCadastros = new javax.swing.JMenu();
        miCadastroCategoria = new javax.swing.JMenuItem();
        miCadastroProduto = new javax.swing.JMenuItem();
        mbRelatorios = new javax.swing.JMenu();
        miRelatorioCategoria = new javax.swing.JMenuItem();
        miRelatorioProdutos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Vendas");

        mbCadastros.setText("Cadastros");

        miCadastroCategoria.setText("Categoria");
        miCadastroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroCategoriaActionPerformed(evt);
            }
        });
        mbCadastros.add(miCadastroCategoria);

        miCadastroProduto.setText("Produto");
        miCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroProdutoActionPerformed(evt);
            }
        });
        mbCadastros.add(miCadastroProduto);

        mbSistemaVendas.add(mbCadastros);

        mbRelatorios.setText("Relatórios");

        miRelatorioCategoria.setText("Categorias");
        miRelatorioCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatorioCategoriaActionPerformed(evt);
            }
        });
        mbRelatorios.add(miRelatorioCategoria);

        miRelatorioProdutos.setText("Produtos");
        miRelatorioProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatorioProdutosActionPerformed(evt);
            }
        });
        mbRelatorios.add(miRelatorioProdutos);

        mbSistemaVendas.add(mbRelatorios);

        setJMenuBar(mbSistemaVendas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCadastroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroCategoriaActionPerformed
       CadastroCategoriaView cadCategoriaView = new CadastroCategoriaView(this);
       cadCategoriaView.setVisible(true);
    }//GEN-LAST:event_miCadastroCategoriaActionPerformed

    private void miCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroProdutoActionPerformed
        CadastroProdutoView cadProdutoView = new CadastroProdutoView(this);
        cadProdutoView.setVisible(true);
    }//GEN-LAST:event_miCadastroProdutoActionPerformed

    private void miRelatorioCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioCategoriaActionPerformed
        RelatorioCategoriasView relCategoriaView = new RelatorioCategoriasView(this);
        relCategoriaView.setVisible(true);
    }//GEN-LAST:event_miRelatorioCategoriaActionPerformed

    private void miRelatorioProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioProdutosActionPerformed
        RelatorioProdutosView relProdutoView = new RelatorioProdutosView(this);
        relProdutoView.setVisible(true);
    }//GEN-LAST:event_miRelatorioProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaVendasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mbCadastros;
    private javax.swing.JMenu mbRelatorios;
    private javax.swing.JMenuBar mbSistemaVendas;
    private javax.swing.JMenuItem miCadastroCategoria;
    private javax.swing.JMenuItem miCadastroProduto;
    private javax.swing.JMenuItem miRelatorioCategoria;
    private javax.swing.JMenuItem miRelatorioProdutos;
    // End of variables declaration//GEN-END:variables
}
