package Visao;

import Modelo.Categoria;
import Modelo.Produto;
import java.util.ArrayList;

public class SistemaVendasView extends javax.swing.JFrame {

    private ArrayList<Categoria> categorias;
    private ArrayList<Produto> produtos;
    
    public SistemaVendasView() {
        this.categorias = new ArrayList<Categoria>();
        this.produtos = new ArrayList<Produto>();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbSistemaVendas = new javax.swing.JMenuBar();
        mnCadastros = new javax.swing.JMenu();
        miCadastroCategoria = new javax.swing.JMenuItem();
        miCadastroProduto = new javax.swing.JMenuItem();
        mnRelatorios = new javax.swing.JMenu();
        miRelatorioCategorias = new javax.swing.JMenuItem();
        miRelatorioProdutos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Vendas");

        mnCadastros.setText("Cadastros");

        miCadastroCategoria.setText("Categoria");
        miCadastroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroCategoriaActionPerformed(evt);
            }
        });
        mnCadastros.add(miCadastroCategoria);

        miCadastroProduto.setText("Produto");
        miCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroProdutoActionPerformed(evt);
            }
        });
        mnCadastros.add(miCadastroProduto);

        mbSistemaVendas.add(mnCadastros);

        mnRelatorios.setText("Relatórios");

        miRelatorioCategorias.setText("Categorias");
        miRelatorioCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatorioCategoriasActionPerformed(evt);
            }
        });
        mnRelatorios.add(miRelatorioCategorias);

        miRelatorioProdutos.setText("Produtos");
        miRelatorioProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatorioProdutosActionPerformed(evt);
            }
        });
        mnRelatorios.add(miRelatorioProdutos);

        mbSistemaVendas.add(mnRelatorios);

        setJMenuBar(mbSistemaVendas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCadastroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroCategoriaActionPerformed
        // Criar o objetivo da View que será exibida
        CadastroCategoriaView cadCategoriaView = new CadastroCategoriaView();
        //Exibir a View
        cadCategoriaView.setVisible(true);
    }//GEN-LAST:event_miCadastroCategoriaActionPerformed

    private void miCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroProdutoActionPerformed
        CadastroProdutoView cadProdutoView = new CadastroProdutoView();
        cadProdutoView.setVisible(true);
    }//GEN-LAST:event_miCadastroProdutoActionPerformed

    private void miRelatorioCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioCategoriasActionPerformed
        RelatorioCategoriasView relCategoriasView = new RelatorioCategoriasView();
        relCategoriasView.setVisible(true);
    }//GEN-LAST:event_miRelatorioCategoriasActionPerformed

    private void miRelatorioProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioProdutosActionPerformed
        RelatorioProdutosView relProdutosView = new RelatorioProdutosView();
        relProdutosView.setVisible(true);
    }//GEN-LAST:event_miRelatorioProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaVendasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mbSistemaVendas;
    private javax.swing.JMenuItem miCadastroCategoria;
    private javax.swing.JMenuItem miCadastroProduto;
    private javax.swing.JMenuItem miRelatorioCategorias;
    private javax.swing.JMenuItem miRelatorioProdutos;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenu mnRelatorios;
    // End of variables declaration//GEN-END:variables
}
